site_name: ChengX的数字图像处理课程作业
site_url: https://github.com/chengx-coding/chengx-coding.github.io.git
site_description: Project documentation with Markdown.
site_author: ChengX
#repo_url: 
theme: mkdocs
pages:
- Home: index.md
- Demos:
  - Demo 1: helloworld.md