title: ChengX的数字图像处理课程实验
description: Digital Image Processing Experiments
theme: jekyll-theme-cayman
encoding: utf-8

permalink: helloworld.md
permalink: qt.md
permalink: exp01.md
permalink: exp02.md
permalink: exp03.md
permalink: exp04.md
permalink: exp05.md